import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { testDatabase } from "./database.js";
import { query } from "../server/db.js";
import { Service } from "../server/service.js";

test("notifications persist, isolate recipients, import projects and enforce revoked access", async () => {
  const database = await testDatabase();
  try {
    const service = new Service(database.db);
    const users = ["负责人", "小明", "小明同学", "路人"].map((name) => ({ id: randomUUID(), name, kind: "session" }));
    for (const user of users) await query(database.db, "INSERT INTO users(id,email,name,password_hash) VALUES(?,?,?,?)", [user.id, `${user.id}@test.com`, user.name, "unused"]);
    const [owner, member, other, outsider] = users;
    const project = await service.createProject(owner, { name: "通知测试" });
    await service.addMember(owner, project.id, { userId: member.id });
    await service.addMember(owner, project.id, { email: `${other.id}@test.com`, name: other.name });
    const added = (await service.notifications(member)).items[0];
    assert.equal(added.kind, "member_added");
    assert.equal(added.sender_name, owner.name);
    assert.equal(added.title, "你已加入「通知测试」");
    assert.equal((await service.notifications(other)).unread, 1);
    assert.equal((await service.projects(member))[0].tab_visible, 0);
    await assert.rejects(service.openNotification(outsider, added.id), { status: 404 });
    const opened = await service.openNotification(member, added.id);
    assert.equal(opened.projectId, project.id);
    assert.equal(opened.projects[0].tab_visible, 1);
    assert.equal((await service.notifications(member)).unread, 0);
    const thread = await service.createThread(owner, project.id, { title: "目标迭代" });
    await service.postMessage(owner, thread.id, { body: "@小明同学 请看一下" });
    assert.equal((await service.notifications(member)).unread, 0);
    await service.postMessage(owner, thread.id, { body: "@小明 请处理，@小明 谢谢。@负责人 自己" });
    assert.equal((await service.notifications(owner)).unread, 0);
    let inbox = await service.notifications(member);
    assert.equal(inbox.unread, 1);
    const mention = inbox.items.find((n) => n.kind === "mention");
    assert.equal(mention.sender_name, owner.name);
    assert.ok(mention.title.includes("目标迭代"));
    await service.updateProjectTab(member, project.id, { action: "close" });
    assert.equal((await service.openNotification(member, mention.id)).threadId, thread.id);
    assert.equal((await service.projects(member))[0].tab_visible, 1);
    await service.readNotification(outsider, mention.id);
    await assert.rejects(service.removeMember(member, project.id, other.id), { status: 403 });
    await assert.rejects(service.removeMember(owner, project.id, owner.id), { status: 409 });
    await service.removeMember(owner, project.id, member.id);
    inbox = await new Service(database.db).notifications(member);
    assert.ok(inbox.items.some((n) => n.kind === "member_removed"));
    assert.ok(inbox.items.every((n) => !n.can_open));
    await assert.rejects(service.openNotification(member, mention.id), { status: 403 });
    await assert.rejects(service.openNotification(member, added.id), { status: 403 });
    assert.equal((await service.projects(member)).length, 0);
    await service.readNotification(member);
    assert.equal((await service.notifications(member)).unread, 0);
    await assert.rejects(service.notifications({ ...member, kind: "api" }), { status: 403 });
    for (let i = 0; i < 52; i++) await service.notify(database.db, member.id, project.id, "member_removed", `分页 ${i}`);
    const first = await service.notifications(member);
    const second = await service.notifications(member, first.next);
    assert.equal(first.items.length, 50);
    assert.ok(second.items.length > 0);
    assert.ok(second.items.every((n) => !first.items.some((x) => x.id === n.id)));
    const removed = await service.notifications(member, undefined, { kind: "member_removed", limit: 12 });
    assert.equal(removed.items.length, 12);
    assert.ok(removed.items.every((n) => n.kind === "member_removed"));
    assert.equal(removed.counts.member_removed.total, 53);
    assert.equal(removed.counts.member_removed.unread, 52);
    const nextRemoved = await service.notifications(member, removed.next, { kind: "member_removed", limit: 12 });
    assert.equal(nextRemoved.items.length, 12);
    assert.ok(nextRemoved.items.every((n) => n.kind === "member_removed" && !removed.items.some((x) => x.id === n.id)));
    const mentions = await service.notifications(member, undefined, { kind: "mention", limit: 12 });
    assert.equal(mentions.items.length, 1);
    assert.equal(mentions.next, null);
    const outsiderPage = await service.notifications(outsider, undefined, { kind: "member_removed", limit: 12 });
    assert.equal(outsiderPage.items.length, 0);
    assert.deepEqual(outsiderPage.counts, {});
    await assert.rejects(service.notifications(member, undefined, { kind: "invalid" }));
    await assert.rejects(service.notifications(member, undefined, { limit: "12 UNION SELECT" }));
  } finally { await database.close(); }
});
