ALTER TABLE assistant_replies ADD COLUMN progress VARCHAR(255) NULL;
CREATE TABLE IF NOT EXISTS agent_events (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, message_id CHAR(36) NOT NULL,
 tool VARCHAR(80) NOT NULL, status ENUM('running','completed','failed') NOT NULL,
 input MEDIUMTEXT NOT NULL, output MEDIUMTEXT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), finished_at DATETIME(3) NULL,
 FOREIGN KEY(message_id) REFERENCES messages(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS agent_sessions (
 thread_id CHAR(36) PRIMARY KEY, session_id CHAR(36) NOT NULL,
 checkpoint MEDIUMBLOB NULL, sandbox_id VARCHAR(160) NULL,
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 FOREIGN KEY(thread_id) REFERENCES threads(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS agent_exports (
 export_key CHAR(64) PRIMARY KEY, version_id CHAR(36) NOT NULL,
 FOREIGN KEY(version_id) REFERENCES versions(id) ON DELETE CASCADE
);
