CREATE TABLE IF NOT EXISTS agent_live_output (
  message_id CHAR(36) PRIMARY KEY,
  run_id CHAR(36) NOT NULL,
  step INT NOT NULL DEFAULT 0,
  reasoning TEXT NOT NULL,
  content MEDIUMTEXT NOT NULL,
  truncated BOOLEAN NOT NULL DEFAULT FALSE,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (message_id) REFERENCES messages(id)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
